artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  source_url: https://github.com/deasadiqbal/mlprojrct/raw/main/data.zip
  local_source_file: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion

data_validation:
  root_dir: artifacts/data_validation
  local_file_path: artifacts/data_ingestion/winequality-red.csv
  STATS_FILE: artifacts/data_validation/status.txt

data_transformation:
  root_dir: artifacts/data_transformation
  data_dir: artifacts/data_ingestion/winequality-red.csv

model_training:
  root_dir: artifacts/model_training
  train_data_dir: artifacts/data_transformation/train.csv
  test_data_dir: artifacts/data_transformation/test.csv
  model_name: model.joblib

model_evaluation:
  root_dir: artifacts/model_evaluation
  test_data_dir: artifacts/data_transformation/train.csv
  model_dir: artifacts/model_training/model.joblib
  metrix_filename: artifacts/model_evaluation/metrics.json