artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  source_url: https://github.com/deasadiqbal/mlprojrct/raw/main/data.zip
  local_source_file: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion